# Generated by Django 4.1.1 on 2023-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_admin_empleadoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='perfil',
            field=models.CharField(max_length=255, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='userestado',
            field=models.CharField(max_length=1, verbose_name='Userestado'),
        ),
    ]
