# Generated by Django 4.1.1 on 2023-02-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_admin_correo_alter_admin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='userestado',
            field=models.CharField(max_length=1, verbose_name='Estado'),
        ),
    ]
