# Generated by Django 4.1.1 on 2023-02-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_admin_empleadoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='empleadoid',
        ),
    ]
