# Generated by Django 4.1.1 on 2023-02-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='MM/DD/AAAA', verbose_name='Fecha registro')),
                ('estado', models.CharField(choices=[('Resuelo', 'Resuelo'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, verbose_name='Estado')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
