# Generated by Django 4.1.1 on 2023-01-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('fecha', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha registro')),
                ('activoid', models.CharField(max_length=5, verbose_name='Activoid')),
                ('empleadoid', models.CharField(max_length=11, verbose_name='Empleadoid')),
                ('estado', models.CharField(choices=[('1', 'Resuelo'), ('0', 'Pendiente')], default='0', max_length=1, verbose_name='Estadonovedad')),
            ],
        ),
    ]
