# Generated by Django 4.1.1 on 2023-03-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('Resuelto', 'Resuelto'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
