# Generated by Django 4.1.1 on 2023-02-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='activoid',
            field=models.CharField(max_length=5, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='empleadoid',
            field=models.CharField(max_length=11, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('1', 'Resuelo'), ('0', 'Pendiente')], default='0', max_length=1, verbose_name='Estado'),
        ),
    ]
