# Generated by Django 4.1.1 on 2023-02-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_novedad_activoid_alter_novedad_empleadoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='activoid',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='empleadoid',
        ),
    ]
