# Generated by Django 4.1.1 on 2023-04-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_alter_novedad_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='activo',
        ),
    ]
