# Generated by Django 4.1.1 on 2023-02-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_empleado_cargoid'),
        ('novedades', '0003_remove_novedad_activoid_remove_novedad_empleadoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
