# Generated by Django 4.1.1 on 2023-02-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_novedad_empleadoid_alter_novedad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
    ]
