# Generated by Django 4.1.1 on 2023-02-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_alter_novedad_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='empleadoid',
        ),
    ]
