# Generated by Django 4.1.1 on 2023-02-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_alter_activo_fecha'),
        ('novedades', '0006_remove_novedad_empleadoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='activoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo'),
        ),
    ]
