# Generated by Django 4.1.1 on 2023-02-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0007_novedad_activoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='activoid',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='fecha',
        ),
    ]
