# Generated by Django 4.1.1 on 2023-02-09 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_empleado_cargoid'),
        ('novedades', '0008_remove_novedad_activoid_remove_novedad_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('1', 'Resuelo'), ('0', 'Pendiente')], default='0', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=2, verbose_name='Fecha registro'),
            preserve_default=False,
        ),
    ]
