# Generated by Django 4.1.1 on 2023-02-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0009_novedad_empleadoid_novedad_estado_novedad_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='empleadoid',
        ),
    ]
