# Generated by Django 4.1.1 on 2023-02-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_initial'),
        ('novedades', '0012_alter_novedad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='activoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo'),
        ),
    ]
