# Generated by Django 4.1.1 on 2023-02-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0013_novedad_activoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novedad',
        ),
    ]
