# Generated by Django 4.1.1 on 2023-02-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='estado',
            field=models.CharField(choices=[('Resuelo', 'Resuelo'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
