# Generated by Django 4.1.1 on 2023-01-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaint', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha registro')),
                ('fechaout', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha registro')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('activoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activoid')),
                ('empleadoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleadoid')),
            ],
        ),
    ]
