# Generated by Django 4.1.1 on 2023-02-04 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_remove_activo_empleadoid_activo_situacion_and_more'),
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='activoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fechaout',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha salida'),
        ),
    ]
