# Generated by Django 4.1.1 on 2023-02-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_alter_movimientos_activoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='activoid',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='empleadoid',
        ),
    ]
