# Generated by Django 4.1.1 on 2023-04-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_initial'),
        ('informes', '0002_remove_movimientos_activoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='activoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo'),
        ),
    ]
