# Generated by Django 4.1.1 on 2023-02-07 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_activo_empleadoid'),
        ('usuarios', '0011_empleado_cargoid'),
        ('informes', '0003_remove_movimientos_activoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='activoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
    ]
