# Generated by Django 4.1.1 on 2023-02-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_movimientos_activoid_movimientos_empleadoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='activoid',
        ),
    ]
