# Generated by Django 4.1.1 on 2023-01-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='empleado id')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('ciudadid', models.CharField(max_length=3, verbose_name='Compañiaid')),
                ('cargoid', models.CharField(max_length=3, verbose_name='Cargoid')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado empleado')),
                ('telefono', models.CharField(max_length=150, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
            ],
        ),
    ]
