# Generated by Django 4.1.1 on 2023-02-21 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcargo', models.CharField(max_length=70, verbose_name='Cargo')),
                ('sueldo', models.CharField(blank=True, max_length=10, verbose_name='Sueldo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('documento', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Documento de Identidad')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=150, verbose_name='Correo')),
                ('perfil', models.ImageField(blank=True, default='images/usuarios/default.png', upload_to='images/usuarios')),
                ('compania', models.CharField(choices=[('medellin', 'Medellin'), ('bogota', 'Bogota'), ('cucuta', 'Cucuta'), ('cartagena', 'Cartagena'), ('bucaramanga', 'Bucaramanga'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Compañia')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado empleado')),
                ('telefono', models.CharField(max_length=150, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Nacimiento')),
                ('cargoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cargo', verbose_name='Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
