# Generated by Django 4.1.1 on 2023-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cargo_delete_ciudad_remove_empleado_cargoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Documento de Identidad'),
        ),
    ]
