# Generated by Django 4.1.1 on 2023-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_empleado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Documento de Identidad'),
        ),
    ]
