# Generated by Django 4.1.1 on 2023-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_empleado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nomcargo',
            field=models.CharField(max_length=70, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='sueldo',
            field=models.CharField(max_length=8, verbose_name='Sueldo'),
        ),
    ]
