# Generated by Django 4.1.1 on 2023-02-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_fecha_nacimiento_empleado_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha',
        ),
    ]
