# Generated by Django 4.1.1 on 2023-02-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_cargo_nomcargo_alter_cargo_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='sueldo',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Sueldo'),
        ),
    ]
