# Generated by Django 4.1.1 on 2023-02-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_empleado_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha',
        ),
    ]
