# Generated by Django 4.1.1 on 2023-02-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_cargo_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='sueldo',
            field=models.CharField(max_length=10, verbose_name='Sueldo'),
        ),
    ]
