# Generated by Django 4.1.1 on 2023-02-22 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_empleado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='MM/DD/AAAA', verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
