# Generated by Django 4.1.1 on 2023-02-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_cargo_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sueldo'),
        ),
    ]
