# Generated by Django 4.1.1 on 2023-02-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_cargo_sueldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='sueldo',
        ),
    ]
