# Generated by Django 4.1.1 on 2023-02-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_empleado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha',
            field=models.DateField(default='1', help_text='MM/DD/AAAA', verbose_name='Fecha de nacimiento'),
        ),
    ]
