# Generated by Django 4.1.1 on 2023-02-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_cargo_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='sueldo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sueldo'),
        ),
    ]
