# Generated by Django 4.1.1 on 2023-02-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_cargo_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cargo', verbose_name='Cargo'),
        ),
    ]
