# Generated by Django 4.1.1 on 2023-02-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_empleado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha'),
        ),
    ]
