# Generated by Django 4.1.1 on 2023-03-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=1, help_text='MM/DD/AAAA', verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
