# Generated by Django 4.1.1 on 2023-01-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('1', 'Asignado'), ('0', 'Pendiente')], default='0', max_length=1, verbose_name='Estado'),
        ),
    ]
