# Generated by Django 4.1.1 on 2023-02-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='idactivo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='situacion',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Reparado', 'Reparado'), ('Otro', 'Otro')], default='Otro', max_length=10, verbose_name='Estado activo'),
        ),
    ]
