# Generated by Django 4.1.1 on 2023-01-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('activos', '0002_remove_activo_empleadoid_alter_activo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleadoid'),
        ),
    ]
