# Generated by Django 4.1.1 on 2023-02-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_activo_estado'),
        ('activos', '0003_activo_empleadoid'),
    ]

    operations = [
    ]
