# Generated by Django 4.1.1 on 2023-02-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_merge_0002_alter_activo_estado_0003_activo_empleadoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='empleadoid',
        ),
        migrations.AddField(
            model_name='activo',
            name='situacion',
            field=models.CharField(choices=[('3', 'Nuevo'), ('2', 'Usado'), ('1', 'Reparado'), ('0', 'Disponible')], default='0', max_length=1, verbose_name='Estado activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('1', 'Asignado'), ('0', 'Creado')], default='0', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.CharField(max_length=25, verbose_name='Tipo de dispositivo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='observaciones',
            field=models.TextField(max_length=200, verbose_name='Caracteristicas'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='serial',
            field=models.CharField(max_length=25, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='so',
            field=models.CharField(max_length=10, verbose_name='Sistama operativo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(max_length=10, verbose_name='Caracteristicas'),
        ),
    ]
