# Generated by Django 4.1.1 on 2023-02-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cargo_delete_ciudad_remove_empleado_cargoid_and_more'),
        ('activos', '0005_remove_activo_empleadoid_activo_situacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
    ]
