# Generated by Django 4.1.1 on 2023-04-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_activo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='empleado',
        ),
    ]
