# Generated by Django 4.1.1 on 2023-04-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_remove_empleado_fecha_nacimiento'),
        ('activos', '0006_remove_activo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
    ]
