# Generated by Django 4.1.1 on 2023-02-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_empleadoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='id',
        ),
        migrations.AddField(
            model_name='activo',
            name='idactivo',
            field=models.CharField(default='0', max_length=6, primary_key=True, serialize=False, verbose_name='Numero activo'),
        ),
    ]
