# Generated by Django 4.1.1 on 2023-02-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_remove_activo_id_activo_idactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='idactivo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero activo'),
        ),
    ]
