# Generated by Django 4.1.1 on 2023-04-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_remove_novedad_activo'),
        ('informes', '0002_remove_movimientos_activoid'),
        ('activos', '0007_activo_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
