# Generated by Django 4.1.1 on 2023-04-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0020_remove_empleado_fecha_nacimiento'),
        ('activos', '0008_delete_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('idactivo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Activo')),
                ('serial', models.CharField(max_length=25, verbose_name='Serial')),
                ('so', models.CharField(max_length=10, verbose_name='Sistama operativo')),
                ('marca', models.CharField(max_length=25, verbose_name='Marca')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo de dispositivo')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(max_length=200, verbose_name='Caracteristicas')),
                ('situacion', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Reparado', 'Reparado'), ('Otro', 'Otro')], default='Otro', max_length=10, verbose_name='Estado activo')),
                ('estado', models.CharField(choices=[('1', 'Asignado'), ('0', 'Creado')], default='0', max_length=1, verbose_name='Estado')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
