# Generated by Django 4.1.1 on 2023-02-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_alter_activo_idactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='empleadoid',
        ),
    ]
