# Generated by Django 4.1.1 on 2023-02-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_empleado_documento'),
        ('activos', '0009_remove_activo_empleadoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
    ]
