# Generated by Django 4.1.1 on 2023-02-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_activo_empleadoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='empleadoid',
        ),
    ]
