# Generated by Django 4.1.1 on 2023-02-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_empleado_cargoid'),
        ('activos', '0011_remove_activo_empleadoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empleadoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado'),
        ),
    ]
