# Generated by Django 4.1.1 on 2023-02-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_activo_empleadoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='MM/DD/AAAA', verbose_name='Fecha de registro'),
        ),
    ]
