# Generated by Django 4.1.1 on 2023-02-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_alter_activo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
