# Generated by Django 4.1.1 on 2023-02-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_alter_activo_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
