# Generated by Django 4.1.1 on 2023-02-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0011_empleado_cargoid'),
        ('activos', '0015_delete_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('idactivo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero activo')),
                ('serial', models.CharField(max_length=25, verbose_name='Serial')),
                ('so', models.CharField(max_length=10, verbose_name='Sistama operativo')),
                ('marca', models.CharField(max_length=25, verbose_name='Tipo de dispositivo')),
                ('tipo', models.CharField(max_length=10, verbose_name='Caracteristicas')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(max_length=200, verbose_name='Caracteristicas')),
                ('situacion', models.CharField(choices=[('3', 'Nuevo'), ('2', 'Usado'), ('1', 'Reparado'), ('0', 'Disponible')], default='0', max_length=1, verbose_name='Estado activo')),
                ('estado', models.CharField(choices=[('1', 'Asignado'), ('0', 'Creado')], default='0', max_length=1, verbose_name='Estado')),
                ('empleadoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
