# Generated by Django 4.1.1 on 2023-02-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
