# Generated by Django 4.1.1 on 2023-02-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.CharField(max_length=25, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='situacion',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Reparado', 'Reparado'), ('Disponible', 'Disponible')], default='Disponible', max_length=10, verbose_name='Estado activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(max_length=10, verbose_name='Tipo de dispositivo'),
        ),
    ]
