# Generated by Django 4.1.1 on 2023-02-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_alter_activo_marca_alter_activo_situacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activo',
            old_name='empleadoid',
            new_name='idempleado',
        ),
    ]
